/*
 * Copyright 2026-present Alibaba Inc.
 *
 * Licensed under the Apache License, Version 2.0.
 *
 * J6: cross-read test — paimon-java produces the tantivy archive, paimon-cpp
 * V3 reader consumes it.
 *
 * The fixture (`english_simple.archive` + `english_simple.golden.json`) is
 * generated by `TantivyIndexFixtureGen.java` in the paimon repo using the
 * production `TantivyIndexWriter` + `packIndex` path. Ten pure-ASCII English
 * documents (row_id 0..9) are indexed; for each SearchType we assert the V3
 * reader returns exactly the row_ids the Java side wrote — evidence that
 * archive byte format, schema, and segment-level byte format all line up
 * across the Java/C++ implementations.
 *
 * Architectural cross-checks this test guards:
 *   1. Archive BE big-endian format parsing (ParseArchiveHeader)
 *   2. Multi-segment layout (Java does not force-merge; 20+ files in fixture)
 *   3. Schema interop: `row_id` u64 fast field written by Java, read by C++ V3
 *   4. Tokenizer parity on pure English (SimpleTokenizer ↔ paimon_jieba)
 *   5. row_id caller-supplied invariant: reader returns the exact row_ids
 *      Java wrote (0..9), NOT tantivy-internal doc_ids
 */

#include <algorithm>
#include <cassert>
#include <iostream>
#include <memory>
#include <string>
#include <vector>

#include "arrow/array.h"
#include "arrow/c/bridge.h"
#include "arrow/type.h"
#include "gtest/gtest.h"

#include "paimon/common/utils/path_util.h"
#include "paimon/core/global_index/global_index_file_manager.h"
#include "paimon/core/index/index_path_factory.h"
#include "paimon/fs/local/local_file_system.h"
#include "paimon/global_index/bitmap_global_index_result.h"
#include "paimon/global_index/bitmap_scored_global_index_result.h"
#include "paimon/predicate/full_text_search.h"
#include "paimon/testing/utils/testharness.h"

#include "arrow/ipc/api.h"

#include "paimon/global_index/tantivy/tantivy_archive_layout.h"
#include "paimon/global_index/tantivy/tantivy_defs.h"
#include "paimon/global_index/tantivy/tantivy_global_index.h"
#include "paimon/global_index/tantivy/tantivy_global_index_reader.h"
#include "paimon/global_index/tantivy/tantivy_global_index_writer.h"

#ifndef JIEBA_TEST_DICT_DIR
#error "JIEBA_TEST_DICT_DIR must be set at compile time"
#endif
#ifndef PAIMON_TANTIVY_JAVA_FIXTURE_DIR
#error "PAIMON_TANTIVY_JAVA_FIXTURE_DIR must be set at compile time"
#endif

namespace paimon::tantivy::test {

namespace {

class FixturePathFactory : public IndexPathFactory {
 public:
    explicit FixturePathFactory(const std::string& root) : root_(root) {}
    std::string NewPath() const override {
        assert(false);
        return "";
    }
    std::string ToPath(const std::shared_ptr<IndexFileMeta>&) const override {
        assert(false);
        return "";
    }
    std::string ToPath(const std::string& file_name) const override {
        return PathUtil::JoinPath(root_, file_name);
    }
    bool IsExternalPath() const override { return false; }

 private:
    std::string root_;
};

class JavaCompatTest : public ::testing::Test {
 public:
    void SetUp() override {
        setenv(kJiebaDictDirEnv, JIEBA_TEST_DICT_DIR, /*overwrite=*/1);
    }

    /// Build a V3 TantivyGlobalIndexReader on top of the Java-produced fixture.
    /// `fixture_name` is relative to `PAIMON_TANTIVY_JAVA_FIXTURE_DIR`.
    std::shared_ptr<GlobalIndexReader> OpenFixture(const std::string& fixture_name) {
        std::string fixture_dir = PAIMON_TANTIVY_JAVA_FIXTURE_DIR;
        std::string archive_path = PathUtil::JoinPath(fixture_dir, fixture_name);

        auto file_status = fs_->GetFileStatus(archive_path).value();
        int64_t file_size = file_status->GetLen();
        EXPECT_GT(file_size, 4) << "fixture archive must exist and be > 4 bytes";

        // Empty metadata (options not needed for cross-read — we use defaults)
        std::string metadata_json = "{}";
        auto meta_bytes = std::make_shared<Bytes>(metadata_json, pool_.get());

        // range_end = 9 (10 docs, row_ids 0..9 inclusive)
        GlobalIndexIOMeta io_meta(archive_path, file_size, /*range_end=*/9, meta_bytes);

        std::map<std::string, std::string> options;
        auto global_index = std::make_shared<TantivyGlobalIndex>(options);
        auto path_factory = std::make_shared<FixturePathFactory>(fixture_dir);
        auto file_reader = std::make_shared<GlobalIndexFileManager>(fs_, path_factory);

        auto data_type = arrow::struct_({arrow::field("f0", arrow::utf8())});
        auto c_schema = std::make_unique<::ArrowSchema>();
        EXPECT_TRUE(arrow::ExportType(*data_type, c_schema.get()).ok());

        auto reader_res =
            global_index->CreateReader(c_schema.get(), file_reader, {io_meta}, pool_);
        EXPECT_TRUE(reader_res.ok()) << reader_res.status().ToString();
        return reader_res.value();
    }

    std::shared_ptr<FullTextSearch> BuildFts(FullTextSearch::SearchType type,
                                              const std::string& query) {
        return std::make_shared<FullTextSearch>(
            /*_field_name=*/"f0",
            /*_limit=*/std::optional<int32_t>{},
            /*_query=*/query,
            /*_search_type=*/type,
            /*_pre_filter=*/std::optional<RoaringBitmap64>{});
    }

    /// Run the search and return the sorted row_ids from the result bitmap.
    std::vector<int64_t> RunSearchRowIds(const std::shared_ptr<GlobalIndexReader>& reader,
                                         FullTextSearch::SearchType type,
                                         const std::string& query) {
        auto fts = BuildFts(type, query);
        auto result = reader->VisitFullTextSearch(fts);
        EXPECT_TRUE(result.ok()) << result.status().ToString();
        std::shared_ptr<GlobalIndexResult> r = result.value();

        const RoaringBitmap64* bitmap = nullptr;
        if (auto plain = std::dynamic_pointer_cast<BitmapGlobalIndexResult>(r)) {
            auto b = plain->GetBitmap();
            EXPECT_TRUE(b.ok()) << b.status().ToString();
            bitmap = b.value();
        } else if (auto scored = std::dynamic_pointer_cast<BitmapScoredGlobalIndexResult>(r)) {
            auto b = scored->GetBitmap();
            EXPECT_TRUE(b.ok()) << b.status().ToString();
            bitmap = b.value();
        }
        EXPECT_TRUE(bitmap != nullptr);
        if (bitmap == nullptr) return {};

        std::vector<int64_t> out;
        for (auto it = bitmap->Begin(); it != bitmap->End(); ++it) {
            out.push_back(static_cast<int64_t>(*it));
        }
        std::sort(out.begin(), out.end());
        return out;
    }

 protected:
    std::shared_ptr<MemoryPool> pool_ = GetDefaultPool();
    std::shared_ptr<FileSystem> fs_ = std::make_shared<LocalFileSystem>();
};

}  // namespace

// ============================================================================
// 1. Archive basics: opening the Java-produced fixture succeeds
// ============================================================================

TEST_F(JavaCompatTest, OpenJavaArchiveSucceeds) {
    auto reader = OpenFixture("english_simple.archive");
    ASSERT_TRUE(reader != nullptr);
}

// ============================================================================
// 2. MATCH_ALL — single and multi-term
// ============================================================================

TEST_F(JavaCompatTest, MatchAll_Apple) {
    auto reader = OpenFixture("english_simple.archive");
    auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ALL, "apple");
    // Docs containing "apple": 0 ("apple banana cherry"), 1 ("apple durian"),
    // 4 ("apple cherry fig"), 7 ("apple")
    EXPECT_EQ(ids, (std::vector<int64_t>{0, 1, 4, 7}));
}

TEST_F(JavaCompatTest, MatchAll_AppleBanana_Intersection) {
    auto reader = OpenFixture("english_simple.archive");
    auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ALL, "apple banana");
    // Only doc 0 contains both "apple" and "banana"
    EXPECT_EQ(ids, (std::vector<int64_t>{0}));
}

// ============================================================================
// 3. MATCH_ANY — union
// ============================================================================

TEST_F(JavaCompatTest, MatchAny_DurianElderberry_Union) {
    auto reader = OpenFixture("english_simple.archive");
    auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ANY,
                                "durian elderberry");
    // durian: 1, 6   elderberry: 5, 8   union: {1, 5, 6, 8}
    EXPECT_EQ(ids, (std::vector<int64_t>{1, 5, 6, 8}));
}

// ============================================================================
// 4. PHRASE — consecutive term order matters
// ============================================================================

TEST_F(JavaCompatTest, Phrase_AppleBanana) {
    auto reader = OpenFixture("english_simple.archive");
    auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::PHRASE, "apple banana");
    // Only doc 0 has "apple banana" as consecutive phrase
    EXPECT_EQ(ids, (std::vector<int64_t>{0}));
}

TEST_F(JavaCompatTest, Phrase_BananaCherry) {
    auto reader = OpenFixture("english_simple.archive");
    auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::PHRASE, "banana cherry");
    // "banana cherry" consecutive in doc 0 ("apple banana cherry") and doc 2 ("banana cherry")
    EXPECT_EQ(ids, (std::vector<int64_t>{0, 2}));
}

// ============================================================================
// 5. PREFIX — byte-level (not tokenized) via RegexQuery
// ============================================================================

TEST_F(JavaCompatTest, Prefix_Ap) {
    auto reader = OpenFixture("english_simple.archive");
    auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::PREFIX, "ap");
    // Tokens starting with "ap": "apple" → docs 0, 1, 4, 7
    EXPECT_EQ(ids, (std::vector<int64_t>{0, 1, 4, 7}));
}

// ============================================================================
// 6. WILDCARD — glob-style via regex
// ============================================================================

TEST_F(JavaCompatTest, Wildcard_Err) {
    auto reader = OpenFixture("english_simple.archive");
    auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::WILDCARD, "*err*");
    // Tokens matching *err*: "cherry" (0,2,4,6,9), "elderberry" (5,8)
    EXPECT_EQ(ids, (std::vector<int64_t>{0, 2, 4, 5, 6, 8, 9}));
}

// ============================================================================
// 7. row_id invariant — must return the *caller-supplied* row_ids (not doc_ids)
// ============================================================================

TEST_F(JavaCompatTest, AllDocsReachableByRowId) {
    auto reader = OpenFixture("english_simple.archive");
    // Union of all terms matches all 10 docs.
    auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ANY,
                                "apple banana cherry durian fig grape elderberry");
    EXPECT_EQ(ids, (std::vector<int64_t>{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}));
    // This confirms Java wrote row_ids 0..9 via `addDocument(rowId, text)` and
    // paimon-cpp V3 reader extracted them via fast_fields().u64("row_id") —
    // the schema B1 invariant survives round-trip across implementations.
}

// ============================================================================
// 8. Probe: real paimon-java production archive (handed over by Java team).
//    Data was claimed to be (id INT, content STRING) with 5 rows but ids
//    rewritten multiple times; dump layout + per-term hits so caller can
//    reverse-engineer what's actually inside.
// ============================================================================

TEST_F(JavaCompatTest, ProductionSampleProbe) {
    const std::string fixture_name = "production_sample.archive";
    const std::string fixture_dir = PAIMON_TANTIVY_JAVA_FIXTURE_DIR;
    const std::string archive_path = PathUtil::JoinPath(fixture_dir, fixture_name);

    // 1) parse archive header, dump layout
    auto stream_res = fs_->Open(archive_path);
    ASSERT_TRUE(stream_res.ok()) << stream_res.status().ToString();
    std::shared_ptr<InputStream> stream = std::move(stream_res).value();
    auto layout_res = ParseArchiveHeader(stream.get());
    ASSERT_TRUE(layout_res.ok()) << layout_res.status().ToString();
    const auto& layout = layout_res.value();
    std::cerr << "[PROBE] archive=" << fixture_name
              << " file_count=" << layout.count << "\n";
    for (std::size_t i = 0; i < layout.count; ++i) {
        std::cerr << "  [" << i << "] " << layout.names[i]
                  << "  offset=" << layout.offsets[i]
                  << "  length=" << layout.lengths[i] << "\n";
    }

    // 2) open reader and print the schema-declared tokenizer name
    auto reader = OpenFixture(fixture_name);
    ASSERT_TRUE(reader != nullptr);

    // 3) scan for keywords we'd expect based on user-provided text samples
    //    ("Apache Paimon / full-text search / vector / lumina / streaming / ...").
    //    tokenizer is "default" — lowercased word-granular tokens.
    const std::vector<std::string> probes = {
            "apache",     "paimon",  "is",        "a",          "lake",
            "format",     "supports", "full",     "text",       "search",
            "in",         "vector",  "similarity", "using",     "lumina",
            "streaming",  "and",     "batch",    "processing", "engine",
    };

    std::cerr << "[PROBE] MATCH_ALL per-term row_ids:\n";
    for (const auto& term : probes) {
        auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ALL, term);
        std::cerr << "  " << term << " -> [";
        for (std::size_t i = 0; i < ids.size(); ++i) {
            if (i > 0) std::cerr << ", ";
            std::cerr << ids[i];
        }
        std::cerr << "]\n";
    }

    // 4) union of everything to see every row_id present in the archive
    std::string all_terms;
    for (const auto& t : probes) {
        if (!all_terms.empty()) all_terms += " ";
        all_terms += t;
    }
    auto all_ids = RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ANY, all_terms);
    std::cerr << "[PROBE] union all probe terms -> row_id count=" << all_ids.size() << " [";
    for (std::size_t i = 0; i < all_ids.size(); ++i) {
        if (i > 0) std::cerr << ", ";
        std::cerr << all_ids[i];
    }
    std::cerr << "]\n";

    // 5) a few common phrases from the user's snippet
    for (const auto& phrase : std::vector<std::string>{
                 "apache paimon", "full text", "vector similarity", "streaming and batch"}) {
        auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::PHRASE, phrase);
        std::cerr << "[PROBE] PHRASE \"" << phrase << "\" -> [";
        for (std::size_t i = 0; i < ids.size(); ++i) {
            if (i > 0) std::cerr << ", ";
            std::cerr << ids[i];
        }
        std::cerr << "]\n";
    }

    // sanity: the archive is readable at all — at least one probe term hits.
    bool any_hit = false;
    for (const auto& term : probes) {
        auto ids = RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ALL, term);
        if (!ids.empty()) {
            any_hit = true;
            break;
        }
    }
    EXPECT_TRUE(any_hit) << "no probe term hit; archive may be empty or schema mismatched";
}

// ============================================================================
// 9. Reverse direction: paimon-cpp writes with tokenizer="default" → fixture
//    consumed by paimon-java test. This test emits the archive into
//    test/test_data/cpp_tantivy_fixtures/english_default.archive and
//    round-trips it through the cpp reader first (schema-driven tokenizer
//    dispatch picks "default" automatically via P-TK).
// ============================================================================

namespace {

/// GlobalIndexFileWriter that emits to a single fixed filename under `root`.
/// Mirrors paimon-java's `FixedNameLocalFileWriter` from
/// `TantivyIndexFixtureGen.java`: `newFileName(prefix)` ignores the prefix and
/// always returns the caller-chosen name. Used to produce a stable fixture
/// path consumed by the paimon-java cross-read test.
class FixedNameGlobalIndexFileWriter : public GlobalIndexFileWriter {
 public:
    FixedNameGlobalIndexFileWriter(std::shared_ptr<FileSystem> fs, std::string root,
                                   std::string fixed_name)
        : fs_(std::move(fs)), root_(std::move(root)), fixed_name_(std::move(fixed_name)) {}

    Result<std::string> NewFileName(const std::string& /*prefix*/) const override {
        return fixed_name_;
    }
    std::string ToPath(const std::string& file_name) const override {
        return PathUtil::JoinPath(root_, file_name);
    }
    Result<std::unique_ptr<OutputStream>> NewOutputStream(
        const std::string& file_name) const override {
        return fs_->Create(ToPath(file_name), /*overwrite=*/true);
    }
    Result<int64_t> GetFileSize(const std::string& file_name) const override {
        PAIMON_ASSIGN_OR_RAISE(std::unique_ptr<FileStatus> file_status,
                               fs_->GetFileStatus(ToPath(file_name)));
        return file_status->GetLen();
    }

 private:
    std::shared_ptr<FileSystem> fs_;
    std::string root_;
    std::string fixed_name_;
};

/// Same 10-doc English corpus paimon-java uses in TantivyIndexFixtureGen
/// (pure ASCII, no punctuation inside words). SimpleTokenizer (tantivy's
/// "default") tokenizes identically on both sides for this subset, so the
/// golden row_ids match byte-for-byte between cpp-write and java-read.
constexpr const char* kEnglishDocs[] = {
    "apple banana cherry",    // 0
    "apple durian",           // 1
    "banana cherry",          // 2
    "fig grape",              // 3
    "apple cherry fig",       // 4
    "banana elderberry",      // 5
    "cherry durian",          // 6
    "apple",                  // 7
    "grape fig elderberry",   // 8
    "cherry fig",             // 9
};

}  // namespace

TEST_F(JavaCompatTest, CppWriteDefaultTokenizerForJavaCrossRead) {
    // 1) Produce an archive into test/test_data/cpp_tantivy_fixtures/ via the
    //    production TantivyGlobalIndexWriter, configured with tantivy's
    //    built-in "default" tokenizer (same as paimon-java's TEXT field).
    const std::string out_dir = PAIMON_TANTIVY_CPP_FIXTURE_DIR;
    const std::string fixture_name = "english_default.archive";
    // Ensure dir exists (CMake does NOT create it automatically).
    {
        auto mk = fs_->Mkdirs(out_dir);
        ASSERT_TRUE(mk.ok()) << mk.ToString();
    }
    // Clean any prior fixture so each test run writes fresh bytes.
    {
        const std::string archive_path_cleanup = PathUtil::JoinPath(out_dir, fixture_name);
        auto existing = fs_->GetFileStatus(archive_path_cleanup);
        if (existing.ok()) {
            ASSERT_TRUE(fs_->Delete(archive_path_cleanup, false).ok());
        }
    }

    auto file_writer =
        std::make_shared<FixedNameGlobalIndexFileWriter>(fs_, out_dir, fixture_name);

    auto data_type = arrow::struct_({arrow::field("f0", arrow::utf8())});

    std::map<std::string, std::string> options{
        {kTantivyWriteTokenizer, "default"},
    };
    auto writer_res = TantivyGlobalIndexWriter::Create(
        "f0", data_type, file_writer, options, pool_);
    ASSERT_TRUE(writer_res.ok()) << writer_res.status().ToString();
    auto writer = writer_res.value();

    // Build an arrow batch from kEnglishDocs.
    std::string json = "[";
    for (std::size_t i = 0; i < sizeof(kEnglishDocs) / sizeof(kEnglishDocs[0]); ++i) {
        if (i > 0) json += ",";
        json += "[\"";
        json += kEnglishDocs[i];
        json += "\"]";
    }
    json += "]";
    auto array = arrow::ipc::internal::json::ArrayFromJSON(data_type, json).ValueOrDie();
    ::ArrowArray c_array;
    ASSERT_TRUE(arrow::ExportArray(*array, &c_array).ok());
    ASSERT_TRUE(writer->AddBatch(&c_array).ok());
    auto metas_res = writer->Finish();
    ASSERT_TRUE(metas_res.ok()) << metas_res.status().ToString();
    ASSERT_EQ(metas_res.value().size(), 1u);
    const auto& meta = metas_res.value().front();
    const std::string archive_path = meta.file_path;
    std::cerr << "[CPP-WRITE] archive_path=" << archive_path
              << " file_size=" << meta.file_size
              << " range_end=" << meta.range_end << "\n";
    ASSERT_EQ(meta.range_end, 9);

    // 2) Archive header sanity: 16+ files, meta.json present, tokenizer in schema.
    auto stream_res = fs_->Open(archive_path);
    ASSERT_TRUE(stream_res.ok()) << stream_res.status().ToString();
    std::shared_ptr<InputStream> stream = std::move(stream_res).value();
    auto layout_res = ParseArchiveHeader(stream.get());
    ASSERT_TRUE(layout_res.ok()) << layout_res.status().ToString();
    const auto& layout = layout_res.value();
    std::cerr << "[CPP-WRITE] file_count=" << layout.count << "\n";
    bool has_meta_json = false;
    for (std::size_t i = 0; i < layout.count; ++i) {
        if (layout.names[i] == "meta.json") has_meta_json = true;
    }
    EXPECT_TRUE(has_meta_json);

    // 3) Round-trip through the cpp reader first — P-TK must auto-register
    //    "default" from the schema so the search path works without passing
    //    any reader-side tokenizer config.
    //    Build a reader directly off the archive path (mirrors OpenFixture
    //    but rooted at the cpp fixtures dir).
    auto file_status = fs_->GetFileStatus(archive_path).value();
    int64_t file_size = file_status->GetLen();
    auto meta_bytes = std::make_shared<Bytes>(std::string("{}"), pool_.get());
    GlobalIndexIOMeta io_meta(archive_path, file_size, /*range_end=*/9, meta_bytes);
    auto reader_factory = std::make_shared<TantivyGlobalIndex>(
        std::map<std::string, std::string>{});
    auto reader_path_factory = std::make_shared<FixturePathFactory>(out_dir);
    auto reader_file_mgr =
        std::make_shared<GlobalIndexFileManager>(fs_, reader_path_factory);

    auto c_schema = std::make_unique<::ArrowSchema>();
    ASSERT_TRUE(arrow::ExportType(*data_type, c_schema.get()).ok());

    auto reader_res = reader_factory->CreateReader(
        c_schema.get(), reader_file_mgr, {io_meta}, pool_);
    ASSERT_TRUE(reader_res.ok()) << reader_res.status().ToString();
    auto reader = reader_res.value();

    // Golden expectations (identical to paimon-java's english_simple.golden.json)
    EXPECT_EQ(RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ALL, "apple"),
              (std::vector<int64_t>{0, 1, 4, 7}));
    EXPECT_EQ(
        RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ALL, "apple banana"),
        (std::vector<int64_t>{0}));
    EXPECT_EQ(RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ANY,
                              "durian elderberry"),
              (std::vector<int64_t>{1, 5, 6, 8}));
    EXPECT_EQ(RunSearchRowIds(reader, FullTextSearch::SearchType::PHRASE, "apple banana"),
              (std::vector<int64_t>{0}));
    EXPECT_EQ(RunSearchRowIds(reader, FullTextSearch::SearchType::PHRASE, "banana cherry"),
              (std::vector<int64_t>{0, 2}));
    EXPECT_EQ(RunSearchRowIds(reader, FullTextSearch::SearchType::PREFIX, "ap"),
              (std::vector<int64_t>{0, 1, 4, 7}));
    EXPECT_EQ(RunSearchRowIds(reader, FullTextSearch::SearchType::WILDCARD, "*err*"),
              (std::vector<int64_t>{0, 2, 4, 5, 6, 8, 9}));
    EXPECT_EQ(RunSearchRowIds(reader, FullTextSearch::SearchType::MATCH_ANY,
                              "apple banana cherry durian fig grape elderberry"),
              (std::vector<int64_t>{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}));

    std::cerr << "[CPP-WRITE] SUCCESS: archive ready for paimon-java read at " << archive_path
              << "\n";
}

}  // namespace paimon::tantivy::test
